#!/bin/bash

echo 'remove old kernel'
yum -y remove kernel*
# yum -y --disablerepo='*' --enablerepo=elrepo-kernel install kernel-ml* #
yum -y --disablerepo='*' --enablerepo=elrepo-kernel install kernel-ml kernel-ml-headers kernel-ml-tools kernel-ml-tools-libs

grub2-mkconfig -o /boot/grub2/grub.cfg
grub2-set-default 0

echo 'install softwares'
yum -y upgrade
yum -y install rsync git screen vim nano htop golang tmux mtr traceroute 

echo 'enable bbr'
modprobe tcp_bbr
echo "tcp_bbr" >> /etc/modules-load.d/modules.conf
echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
sysctl -p
sysctl net.ipv4.tcp_available_congestion_control
sysctl net.ipv4.tcp_congestion_control

echo 'set iptables rules for ssh'
iptables -A INPUT -p tcp -m tcp --dport 12345 -j ACCEPT

echo 'add user chinory'
useradd -m -G wheel chinory
