#!/bin/bash

echo 'install epel-release'
yum -y install epel-release

echo 'use iptables instead of firewalld'
systemctl stop firewalld
systemctl disable firewalld

echo 'config sshd'
sed -i 's/^#\(Port\) .*$/\1 12345/; s/^\(PasswordAuthentication\) .*$/\1 no/; s/^#\(ClientAliveInterval\) .*$/\1 60/; s/^#\(ClientAliveCountMax\) .*$/\1 3/; s/^#\(UseDNS\) .*$/\1 no/;' /etc/ssh/sshd_config
systemctl restart sshd

echo 'switch to elrepo-kernel'
rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
yum -y --disablerepo='*' --enablerepo=elrepo-kernel install kernel-ml

echo 'config grub'
sed -i 's/\(^GRUB_TIMEOUT=\).*/\11/; s/\(^GRUB_DEFAULT=\).*/\1saved/; /^GRUB_SAVEDEFAULT=/d; /^GRUB_DEFAULT=/a GRUB_SAVEDEFAULT=true' /etc/default/grub
grub2-mkconfig -o /boot/grub2/grub.cfg
grub2-set-default 0


#echo 'reboot'
#sleep 1 && reboot &
